# This workflow deploys Storybook to GitHub pages

name: Deploy Storybook

on:
  push:
    branches: [main]
    paths:
      - 'src/**'
      - 'stories/**'
      - 'public/**'
      - 'typings/**'
      - '.storybook/**'
      - 'package.json'
      - 'package-lock.json'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build Storybook
        run: |
          npm ci
          npm run build-storybook
      - name: Deploy Storybook
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs-build
          user_name: '${{ github.actor }}'
          user_email: '${{ github.actor }}@users.noreply.github.com'
