name: Quality check (lint + run tests)

on:
  - pull_request:
      branches:
        - main


jobs:
  lint_files:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v2
      - name: Check packege.json verson in main
        run:
      - name: Install dependencies
        run: yarn
      - name: Run ESLint
        run: yarn lint
