# This workflow runs lint and type checking scripts

name: Quality check (lint + type checking)

on:
  pull_request:

jobs:
  run-linters:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Run ESLint
        run: npm run lint
      - name: Check types
        run: npm run check-types
